version: 2.1
jobs:
  buildandtest_linux_latest:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: python -m pip install .
      - run: python -m pytest
workflows:
  main:
    jobs:
      - buildandtest_linux_latest