version: 2.1
jobs:
  buildandtest_linux_latest:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: python3 -m pip install .
        - name: Deploy package and dependencies
      - run: python3 -m pytest
        - name: Test package
  buildandtest_win_latest:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
    steps:
      - checkout
      - run: python -m pip install .
        - name: Deploy package and dependencies
      - run: python -m pytest
        - name: Test package
workflows:
  main:
    jobs:
      - buildandtest_linux_latest
      - buildandtest_win_latest