version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  buildandtest:
    executor: python/default
    steps:
      - checkout
      - run: python -m pip install .
      - run: python -m pytest
workflows:
  main:
    jobs:
      - buildandtest