version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: python -m pip install .
  test:
    executor: python/default
    steps:
      - run: python -m pytest
workflows:
  main:
    jobs:
      - build
      - python/test:
          requires:
            - build